language: ruby

sudo: false

rvm:
  - '1.9.3'
  - '2.2'

env:
  global: FOO='bar'
  matrix:
    - RAKE_TASK=echo
    - RAKE_TASK=test

script:
  - echo $FOO
  - rake $RAKE_TASK

services:
  - redis
  - elasticsearch
