language: ruby

rvm:
  - '1.9.3'
  - '2.2'

env:
  global: FOO='bar'
  matrix:
    - RAKE_TASK=echo
    - RAKE_TASK=test

matrix:
  allow_failures:
    - rvm: '2.2'

script:
  - echo $FOO
  - rake $RAKE_TASK

services:
  - redis
  - elasticsearch

addons:
  postgresql: "9.3"